AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    Timeout: 5
    MemorySize: 128

Resources:
  ApiWithCors:
    Type: AWS::Serverless::Api
    Properties:
      Name: ChrisLabApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  DadJokeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: backend/dad-joke/
      Environment:
        Variables:
          API_URL: 'https://icanhazdadjoke.com/'
      Events:
        DadJokeApi:
          Type: Api
          Properties:
            Path: /dad-joke
            Method: GET
            RestApiId: !Ref ApiWithCors

  WordCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: backend/word-counter/
      Events:
        WordCounterApi:
          Type: Api
          Properties:
            Path: /word-counter
            Method: POST
            RestApiId: !Ref ApiWithCors

Outputs:
  DadJokeApiUrl:
    Description: "GET a dad joke"
    Value: !Sub "https://${ApiWithCors}.execute-api.${AWS::Region}.amazonaws.com/Prod/dad-joke"

  WordCounterApiUrl:
    Description: "POST text to count words"
    Value: !Sub "https://${ApiWithCors}.execute-api.${AWS::Region}.amazonaws.com/Prod/word-counter"
